search_lyrics:
  description: >
    Fetch song lyrics from Genius.com
  fields:
    api_key:
      description: Genius.com API key
      example: "3SxSxqZJOtz5fYlkFXv-12E-mgripD0XM7v0L091P3Kz22wT9ReCRNg0qmrYeveG"
    artist_name:
      description: Name of the song Artist
      example: Protoje
    song_title:
      description: Name of the song.
      example: 'Mind of a King'
    entity_id:
      description: Entity ID to set attributes on.
      example: sensor.lyrics

