search_lyrics:
  description: >
    Fetch song lyrics from Genius.com
  fields:
    entity_id:
      description: Sensor entity id to attach song data.
      example: sensor.foobar_lyrics
    media_artist:
      description: Name of the Artist.
      example: Protoje
    media_title:
      description: Name of the Song.
      example: 'Mind of a King'
